### PR TITLE
Fix a crash in playerctld

### PR DESCRIPTION
**Pull request by Fendse**
As part of the MPRIS standard, media players may optionally implement the interfaces `org.freedesktop.MediaPlayer2.TrackList` and `org.freedesktop.MediaPlayer2.Playlists` and send signals on those as well as sending `PropertiesChanged` signals for these interfaces' properties. While many players don't do this, some do. `playerctld` notices these messages but fails to understand them, causing it to crash every time a player sent such a message (such as when opening or closing any file in VLC)

These commits prevent that crash, and lay some groundwork for possibly having `playerctld` support those interfaces further in the future.

### CODE REVIEW

**Comment by acrisci** [comment]
Very nice, this looks like a good contribution. I'll review this as soon as I have some time.

**Comment by acrisci** [comment]
The test failure here is legitimate. I can reproduce it locally.

**Comment by acrisci** [comment]
What player are you using to test this?

**Comment by acrisci** [comment]
In `player_method_call_proxy_callback()`, check if the interface they called is supported on the destination player.

**Comment by Fendse** [comment]
> The test failure here is legitimate. I can reproduce it locally.

So could I, and I'm not sure why I didn't notice that myself in the first place.

The error was a null dereference causing playerctld to crash when the only open player is closed. I didn't notice it while dogfooding because I almost never close my web browser (which counts as a player).

But missing the fact that a test was yelling at me is embarrassing.

> In `player_method_call_proxy_callback()`, check if the interface they called is supported on the destination player.

Good point, working on it.

> What player are you using to test this?

I've mainly tested with VLC (version 3.0.11.1) so far, since that's the only player I use that tries to implement either of these two interfaces. Admittedly, that means I didn't test `org.mpris.MediaPlayer2.Playlists` interaction very thoroughly, since I couldn't find an implementation "in the wild" (VLC doesn't support it). VLC's support for `org.mpris.MediaPlayer2.TrackList` is a bit spotty, since there are signals that it should emit but seemingly never does (or at least they don't show up in bustle).

There should probably be proper tests as well, I'll see if I can add some.

**Comment by acrisci** [comment]
I'm going to merge this as it is right now because it's good, but would appreciate some further work on those points.

**Pull request merged**
