### PR TITLE
Add --no-messages flag

### PR DESCRIPTION
**Pull request by pta2002**
This should take care of #108. I made it ignore some messages, but if I need to change anything I will.

### CODE REVIEW

**Comment by pta2002** [comment]
Uh oh I left compile_commands.json in, I'll delete it

**Comment by pta2002** [comment]
Hm I can't figure out why the test is failing, I can't replicate it locally.

**Comment by acrisci** [comment]
It's probably fine. I need to fix that test.

**Comment by acrisci** [comment]
:+1:

**Pull request merged**
